### ISSUE TITLE
CollectSumStat.py

### ISSUE THREAD

**Issue by shahanderkarabetian** [pjweggy/CLADES#2]
Hello,

I'm trying to get the CollectSumStat.py script to run, and I am having issues. When running it on the provided example test_seq.txt file, I get the following error:

```
Traceback (most recent call last):
  File "CollectSumStat.py", line 306, in <module>
    Process(fout,rawdata,delim,nbin,nsites)
  File "CollectSumStat.py", line 18, in Process
    [popsize,Allmat,classlabel]=Dict2Mat(rawdata,delim)
  File "CollectSumStat.py", line 210, in Dict2Mat
    spn=m.group(1)
AttributeError: 'NoneType' object has no attribute 'group'
```

Any thoughts on what the issue is?
Thanks

**Comment by Somnous1998** [comment]
Hello,
        I  met the same problem.
![1652792736(1)](https://user-images.githubusercontent.com/63293232/168817811-27e68a09-12e7-4e5e-a80b-54994e75c66b.png)

Can you tell me if you have found a solution?
thanks

**Comment by Somnous1998** [comment]
Hello,
I met the same problem.
1652792736(1)

Can you tell me if you have found a solution?
thanks a lot

@pjweggy

**Comment by Somnous1998** [comment]
Hello,
I met the same problem.
![1652792900(1)](https://user-images.githubusercontent.com/63293232/168818203-1d73c26d-bcfb-4341-ac67-ce561b2d4f46.png)


Can you tell me if you have found a solution?
thanks a lot

@pjweggy

**Comment by shahanderkarabetian** [comment]
@Somnous1998 Here's what I figured out. I think you just cannot run that script as a standalone. My goal was to use that script on my training data set to make input files for custom model creation. What I ended up doing was running (what would be my) training data set against the provided default data set (All), then took the output files of my data set from that analysis and used it as input for creating the model.

**Comment by Somnous1998** [comment]
> @Somnous1998 Here's what I figured out. I think you just cannot run that script as a standalone. My goal was to use that script on my training data set to make input files for custom model creation. What I ended up doing was running (what would be my) training data set against the provided default data set (All), then took the output files of my data set from that analysis and used it as input for creating the model.

Hi!
    Thanks for your advice.I tried your suggestion.But a new problem has arisen.
![1652945921(1)](https://user-images.githubusercontent.com/63293232/169239154-dfc9f299-b8c1-44ca-a4ac-695df3a43b49.png)
Do you have any suggestion? Very grateful for your help. @pjweggy

**Comment by shahanderkarabetian** [comment]
I think I got that error because a few loci did not have enough variation(?) in them, or some other issue with individual loci. Either way, I had to figure out which loci were producing the error, and removing those loci fixed it. I'm not sure how many loci you have, but try running it on the first 10 or so and see if you still get the error. Also make sure you have at least one sample per defined population in every locus.
